name: wxbuild
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10.9
  - wxpython=4.2.0
  - numpy
  - psutil
  - pip
  - pip:
      - vispy==0.12.1
#  - pip:
#      - -e git+https://github.com/mkkb/vispy.git@dev_073#egg=vispy
